Test workflow (#14)
* fix: workflow ci-cd related to dorny/paths-filter

* refractor: channel_service/chats/web_socket/chat_websocket_consumers.py. aim: check working of github workflow on branch test_workflow

* feat: CI-CD - GCP deployment integration

* refractor: server/api_gateway_django/api_router/views.py. aim: workflow ci-cd gcp integration check

* fix: ci-cd Authenticate to Google Cloud before Set up Google Cloud SDK

* refractor: server/api_gateway_django/api_router/views.py. aim: workflow ci-cd gcp Authenticate to Google Cloud fix check

* fix: ci-cd Install gke-gcloud-auth-plugin

* refractor: server/api_gateway_django/api_router/views.py. aim: workflow fix Install gke-gcloud-auth-plugin checking

* refractor: admin_service/admins/views.py, user_service/users/views.py. aim: ci-cd workflow check for admin & user services

* fix: ci-cd tracking changes by comparing main branch by dorny/paths-filter causes to build all services

* refractor: user_service/users/views.py. aim: ci-cd workflow check running all service or specified service only

* fix: ci-cd fetch depth 2.

* refractor: user_service/users/views.py. aim: ci-cd workflow check running all service or specified service only after updating fetch-depth

* fix: ci-cd github.event.before instead of HEAD~1

* test: ci-cd workflow service specific run

* refractor: splitted the ci-cd.yaml into ci.yaml & cd.yaml

* test: working of ci & cd after spliting. refractor:course_service/courses/views.py user_service/users/views.py

* refractor: cd.yaml workflow_run for automate run of cd after ci

* test: working of ci & cd after automating cd. refractor:course_service/courses/views.py user_service/users/views.py

* refractor: ci.yaml & cd.yaml combined back to ci-cd.yaml

* test: working of ci-cd.yaml after combining ci & cd. refractor:course_service/courses/views.py user_service/users/views.py

* fix: ci-cd.yaml to include multiple deployment for one service. refractor: imagePullPolicy to Always

* refractor: course_service/courses/views.py, user_service/users/views.py. aim: ci-cd workflow check for multiple deployments rollout

* fix: ci-cd.yaml undeclared var deployment inside for loop

* refractor: user_service/users/views.py. aim: ci-cd workflow check for multiple deployments rollout

* refractor: ci-cd changed the branch to main.

diff --git a/.github/workflows/ci-cd.yaml b/.github/workflows/ci-cd.yaml
--- a/.github/workflows/ci-cd.yaml
+++ b/.github/workflows/ci-cd.yaml
@@ -10,11 +10,16 @@ on:
       - 'server/admin_service/**'
       - 'server/course_service/**'
       - 'server/channel_service/**'
+      
 env:
   DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
   DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
   DOCKER_SERVICE_PREFIX_NAME: ${{ vars.DOCKER_SERVICE_PREFIX_NAME }}
   DOCKER_IMAGE_TAG: ${{ vars.DOCKER_IMAGE_TAG }}
+  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
+  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
+  GCP_ZONE: ${{ secrets.GCP_ZONE }}
+  GKE_CLUSTER_NAME: ${{ vars.GKE_CLUSTER_NAME }}
 
 jobs:
   build-and-deploy:
@@ -26,45 +31,95 @@ jobs:
           - name: api_gateway_django
             path: server/api_gateway_django
             deployment: api_gateway-deployment.yaml
+            deployment_names: 
+              - api-gateway
             port: 8000
           - name: user_service
             path: server/user_service
             deployment: user_service-deployment.yaml
+            deployment_names: 
+              - user-service
+              - user-service-supporting
             port: 8001
           - name: admin_service
             path: server/admin_service
             deployment: admin_service-deployment.yaml
+            deployment_names: 
+              - admin-service
             port: 8002
           - name: course_service
             path: server/course_service
             deployment: course_service-deployment.yaml
+            deployment_names: 
+              - course-service
+              - course-service-celery
             port: 8003
           - name: channel_service
             path: server/channel_service
             deployment: channel_service-deployment.yaml
+            deployment_names: 
+              - channel-service
             port: 8004
+            
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
 
+      - name: Check for changes in ${{ matrix.service.name }}
+        id: changes
+        uses: dorny/paths-filter@v3
+        with:
+          # base: ${{ github.event.before }}  # comment once merged to main. Only for comparing the commit with last commit, otherwise it comparing with the main branch even from another branches.
+          filters: |
+            changed:
+              - '${{ matrix.service.path }}/**'
+
       - name: Set up Docker Buildx
+        if: steps.changes.outputs.changed == 'true'
         uses: docker/setup-buildx-action@v2
 
       - name: Log in to Docker Hub
+        if: steps.changes.outputs.changed == 'true'
         uses: docker/login-action@v3
         with:
           username: ${{ env.DOCKER_USERNAME }}
           password: ${{ env.DOCKER_PASSWORD }}
 
-      - name: Check for changes in ${{ matrix.service.name }}
-        id: dorny/paths-filter@v3
-        with:
-          filters: |
-            changed:
-              - '${{ matrix.service.path }}/**'
-
       - name: Build and push image
-        if: steps.paths-filter.outputs.changed == 'true'
+        if: steps.changes.outputs.changed == 'true'
         run: |
           docker build -t ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_SERVICE_PREFIX_NAME }}-${{ matrix.service.name }}:${{ env.DOCKER_IMAGE_TAG }} ${{ matrix.service.path }}
           docker push ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_SERVICE_PREFIX_NAME }}-${{ matrix.service.name }}:${{ env.DOCKER_IMAGE_TAG }}
+
+      - name: Authenticate to Google Cloud
+        if: steps.changes.outputs.changed == 'true'
+        uses: google-github-actions/auth@v1
+        with:
+          credentials_json: "${{ env.GCP_SA_KEY }}"
+
+      - name: Set up Google Cloud SDK
+        if: steps.changes.outputs.changed == 'true'
+        uses: google-github-actions/setup-gcloud@v1
+        with:
+          project_id: ${{ env.GCP_PROJECT_ID }}
+
+      - name: Install gke-gcloud-auth-plugin
+        if: steps.changes.outputs.changed == 'true'
+        run: |
+          gcloud components install gke-gcloud-auth-plugin -q
+          gcloud components update -q
+          which gke-gcloud-auth-plugin || echo "Plugin not found in PATH"
+
+      - name: Configure kubectl
+        if: steps.changes.outputs.changed == 'true'
+        run: |
+          gcloud container clusters get-credentials ${{ env.GKE_CLUSTER_NAME }} --zone ${{ env.GCP_ZONE }} --project ${{ env.GCP_PROJECT_ID }}
+
+      - name: Deploy to GKE
+        if: steps.changes.outputs.changed == 'true'
+        run: |
+          for deployment_name in ${{ join(matrix.service.deployment_names, ' ') }}; do
+            echo "Restarting $deployment_name..."
+            kubectl rollout restart deployment/$deployment_name -n default
+            kubectl rollout status deployment/$deployment_name -n default
+          done
